# Generated by Django 5.0.4 on 2024-04-30 09:07

import autoslug.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("870b31a1-bf62-4c65-bd13-7f8fb9fd4c51"),
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=45, unique=True, verbose_name="Name"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.PositiveBigIntegerField()),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("discount_price", models.PositiveBigIntegerField(default=0)),
                ("is_discounted", models.BooleanField(default=False)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        populate_from="name",
                        unique=True,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Main photo"
                    ),
                ),
                ("is_selling", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("870b31a1-bf62-4c65-bd13-7f8fb9fd4c51"),
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=45, unique=True, verbose_name="Name"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("products", models.ManyToManyField(to="products.product")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
