# Generated by Django 5.0.4 on 2024-04-29 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("02b6c586-90aa-41d1-9f1c-9d495d573e77"),
                editable=False,
                unique=True,
            ),
        ),
    ]
