# Generated by Django 5.0.4 on 2024-04-30 09:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("870b31a1-bf62-4c65-bd13-7f8fb9fd4c51"),
                editable=False,
                unique=True,
            ),
        ),
    ]
