version: '3'
services:
    api:
      build:
        context: . 
        dockerfile: ./docker/django/Dockerfile
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes: 
        - .:/app
        - static_volume:/app/staticfiles
        - media_volume:/app/mediafiles
      ports: 
        - "8000:8000"
      env_file:
        - .env
      depends_on: 
        - postgres-db
      networks: 
        - estate-react
    postgres-db:
      image: postgres:12.0-alpine
      ports:
          - "5433:5432"
      volumes:
          - postgres_data:/var/lib/postgresql/data
      # env_file:
      #   - .env
      environment:
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=admin123456
          - POSTGRES_DB=ecomerce
          
      networks:
          - estate-react
      
networks:
    estate-react:
volumes:
    static_volume: 
    media_volume:
    postgres_data: