# Generated by Django 5.0.4 on 2024-04-29 13:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("f6636214-4b10-4093-ba18-b9ca3fba0066"),
                editable=False,
                unique=True,
            ),
        ),
    ]
