# Generated by Django 5.0.4 on 2024-04-29 19:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9530a392-3486-4165-8499-c416cd2e2015"),
                editable=False,
                unique=True,
            ),
        ),
    ]
