# Generated by Django 5.0.4 on 2024-04-30 09:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("efcc1fcb-a1d4-4805-9e99-c67e76eb20e3"),
                editable=False,
                unique=True,
            ),
        ),
    ]
