# Generated by Django 5.0.4 on 2024-05-12 19:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6ebb2763-bfef-4725-b7ba-f627aecd4ea8"),
                editable=False,
                unique=True,
            ),
        ),
    ]
