# Generated by Django 5.0.4 on 2024-05-13 15:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("02c5eb98-4024-4fb3-8ee4-6d466f938cae"),
                editable=False,
                unique=True,
            ),
        ),
    ]
